name: BookHunt
channels:
		- defaults
		- https://repo.anaconda.com/pkgs/main
		- https://repo.anaconda.com/pkgs/r
		- https://repo.anaconda.com/pkgs/msys2
dependencies:
		- asttokens=2.0.5=pyhd3eb1b0_0
		- bzip2=1.0.8=h2bbff1b_6
		- ca-certificates=2025.2.25=haa95532_0
		- colorama=0.4.6=py313haa95532_0
		- decorator=5.1.1=pyhd3eb1b0_0
		- executing=0.8.3=pyhd3eb1b0_0
		- expat=2.6.4=h8ddb27b_0
		- ipython=8.30.0=py313haa95532_0
		- jedi=0.19.2=py313haa95532_0
		- libffi=3.4.4=hd77b12b_1
		- libmpdec=4.0.0=h827c3e9_0
		- matplotlib-inline=0.1.6=py313haa95532_0
		- openssl=3.0.15=h827c3e9_0
		- parso=0.8.4=py313haa95532_0
		- pip=25.0=py313haa95532_0
		- prompt-toolkit=3.0.43=py313haa95532_0
		- prompt_toolkit=3.0.43=hd3eb1b0_0
		- pure_eval=0.2.2=pyhd3eb1b0_0
		- pygments=2.15.1=py313haa95532_1
		- python=3.13.2=hadb2040_100_cp313
		- python_abi=3.13=0_cp313
		- setuptools=75.8.0=py313haa95532_0
		- six=1.16.0=pyhd3eb1b0_1
		- sqlite=3.45.3=h2bbff1b_0
		- stack_data=0.2.0=pyhd3eb1b0_0
		- tk=8.6.14=h0416ee5_0
		- traitlets=5.14.3=py313haa95532_0
		- tzdata=2025a=h04d1e81_0
		- vc=14.42=haa95532_4
		- vs2015_runtime=14.42.34433=he0abc0d_4
		- wcwidth=0.2.5=pyhd3eb1b0_0
		- wheel=0.45.1=py313haa95532_0
		- xz=5.6.4=h4754444_1
		- zlib=1.2.13=h8cc25b3_1
		- pip:
					- blinker==1.9.0
					- certifi==2025.1.31
					- charset-normalizer==3.4.1
					- click==8.1.8
					- flask==3.1.0
					- greenlet==3.1.1
					- idna==3.10
					- itsdangerous==2.2.0
					- jinja2==3.1.5
					- markupsafe==3.0.2
					- playwright==1.50.0
					- pyee==12.1.1
					- requests==2.32.3
					- typing-extensions==4.12.2
					- urllib3==2.3.0
					- werkzeug==3.1.3
